# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7ca515706f3f4b9ccfd4b1b48c42d53be314dd00b486d5f8a713af7450767ce14c7c716c8948215420222e9bf764b3a768420fd32dead98aa5ce1949059a638

test:
  secret_key_base: 32f469f5104161cc664023c289cbdff191f06952da05ab6c55662bc512e249e91ee12ccfb6e65cff3dd0ae14e1da25dd2900a055505bbc5668205deb4fff4277

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
